create profile christina qiu
pennlabs/website pull request #201
Opened 2023-09-25 15:18 UTC by christinaqiu3

2023-09-27 14:00 UTC, joyliu-q requested changes

2023-09-27 14:00 UTC, joyliu-q commented on src/json/members/chuu.json
> +    "photo": "https://i.imgur.com/QLVYZ5H.png",
Make sure to update this photo! Right now it shows a placeholder.

2023-09-27 14:02 UTC, joyliu-q commented on src/json/members/chuu.json
> +  }
Also, nit: let's add a new line here.

2023-10-01 18:54 UTC, judtinzhang commented
Closing because changes already pushed

2023-10-01 18:54 UTC, closed without merging