Add rachel lee
pennlabs/website pull request #202
Opened 2023-09-27 14:40 UTC by rachllee

2023-09-28 02:09 UTC, joyliu-q requested changes

2023-09-28 02:09 UTC, joyliu-q commented on src/images/about/.high-five.gif.icloud
Can you remove these changes? I think they occur when you try to clone this in your documents tab with automatic icloud backup enabled.

2023-09-28 02:11 UTC, joyliu-q commented on src/images/about/.high-five.gif.icloud
If it makes things easier, you can reclone it onto anther folder that doesn't have icloud backup:

https://www.xda-developers.com/how-stop-desktop-syncing-icloud-macos/

You can also try to make these changes directly through GitHub without setting up a local repo:

https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository

2023-09-30 01:38 UTC, judtinzhang commented
Closing this as Rachel has been added

2023-09-30 01:38 UTC, closed without merging