jamesdoh bio added
pennlabs/website pull request #271
Opened 2024-09-22 15:15 UTC by jamesdoh0109

2024-09-22 16:56 UTC, charisgao commented on src/json/members/dohj0109.json
> +  "team": ["Penn Courses"],
should not be a list

2024-09-22 17:01 UTC, charisgao requested changes
please update team!

2024-09-22 19:38 UTC, jamesdoh0109 commented on src/json/members/dohj0109.json
> +  "team": ["Penn Courses"],
Just changed it, thanks

2024-09-23 03:00 UTC, charisgao approved these changes

2024-09-23 03:01 UTC, merged