added Sritan Motati
pennlabs/website pull request #274
Opened 2024-09-22 17:21 UTC by sritanmotati

2024-09-23 03:03 UTC, charisgao requested changes

2024-09-23 03:03 UTC, charisgao commented on src/json/members/sritanmotati.json
> +    "semester_joined": "2024F",
should be "2024C"

2024-09-23 21:34 UTC, sritanmotati commented on src/json/members/sritanmotati.json
> +    "semester_joined": "2024F",
resolved

2024-09-26 01:44 UTC, Clue88 approved these changes

2024-09-27 02:30 UTC, charisgao approved these changes

2024-09-27 02:30 UTC, merged