Nikhilbio
pennlabs/website pull request #282
Opened 2024-09-25 20:25 UTC by nruia-penn

What is the difference between sem joined 2024A, and sem joined 2024F

2024-09-25 22:55 UTC, Clue88 commented
hey nikhil, there's no such thing as 2024F in our system:

A means spring
B means summer
C means fall

so you'll have to list your semester as 2024C

2024-09-25 22:56 UTC, Clue88 requested changes
see comment

2024-09-26 00:51 UTC, nruia-penn commented
I updated it to 2024C .

2024-09-26 00:52 UTC, nruia-penn reviewed
testing if this will automatically run tests -- didn't work how do I like tell github that I did the requested changes

2024-09-26 01:02 UTC, Clue88 requested changes

2024-09-26 01:02 UTC, Clue88 commented on src/json/members/nikhil.json
> +    "photo": "https://imgur.com/a/aMYgh9l",
looks like this photo is the problem, you'll need to use the link to the actual image file (should end with .jpg), not the link to the imgur page

2024-09-26 01:37 UTC, Clue88 approved these changes

2024-09-26 01:37 UTC, merged