Add kaushik bio
pennlabs/website pull request #290
Opened 2024-09-27 22:20 UTC by Akula112233

2024-09-27 22:21 UTC, joemacd approved these changes
very cool

2024-09-29 16:56 UTC, charisgao requested changes
please rename your file to pennkey.json

2024-11-09 19:05 UTC, charisgao approved these changes
LGTM

2025-09-28 21:28 UTC, zhiyaot approved these changes

2025-09-28 21:38 UTC, Preetam-Jain approved these changes

2025-10-04 21:38 UTC, merged