Updated my team member info card
pennlabs/website pull request #76
Opened 2021-08-11 17:31 UTC by cphalen

2021-08-11 17:47 UTC, KeenWill approved these changes
Looks good ;)

2021-08-11 17:49 UTC, ArmaanT requested changes
lgtm, but can you also move Marta back to the android team?

2021-08-11 19:28 UTC, cphalen commented
How does that look for Marta's information?

2021-08-12 03:11 UTC, ArmaanT approved these changes
LGTM!

2021-08-12 03:11 UTC, merged